### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by streeve** [DorianDepriester/MTEX2Gmsh#1]
I have a few suggestions to improve documentation per openjournals/joss-reviews#2094

Concerning the tutorial:
- [x] Specify matlab, mtex, and gmsh versions required (potentially gcc underlying gmsh)
- [x] Data initialization should have a heading and code block formatting (currently only done for the "Improve" section), ideally pointing out this examples from mtex are being used
- [x] Link to doc page in README (maybe add image)
- [x] In the "Mesh" and "Customize" sections the figures are not directly from code examples - either be very clear about this or add how to obtain these images as part of the tutorial

The example cases are easy to follow and seem to cover the extent of the intended uses, but unit testing is missing. Some recently accepted joss papers using matlab have what seems to be an offline-automated test suite
- [x] Add unit tests

I did not see any API documentation (maybe I am forgetting how to access this in matlab)
- [x] Add API docs

Finally, make sure to add a CONTRIBUTING.md file for Github contributors
- [x] CONTRIBUTING.md

**Comment by DorianDepriester** [comment]
Thank you @streeve for your quick review. All the points you mentioned have been taken into consideration.

Just to mention, the unit test are not that easy to implement on MATLAB. As far as I know, [Code Ocean](https://codeocean.com/) is the easiest way to provide offline test for reproducibility. The link to the related _Capsule_ has been added in ``README.md``.

Considering the API docs, I am not sure to understand its meaning in the MATLAB scripting context. All functions and methods are provided along with help sections (in addition to documentation). For instance, juste type

    help gmshGeo

to get help about the ``gmshGeo`` constructor.

**Comment by streeve** [comment]
Great, thanks

The Code Ocean online environment is quite nice. My only objection is that (as far as I can tell) it only tests one case. Something like https://github.com/vitorsr/SIHR/blob/master/utils/automated_testing.m could work

**Comment by streeve** [comment]
For the API docs, a section just mentioning both `help` (thank you, I haven't actively used matlab in a while) and `methods` to make it easy to explore all options in the class

**Comment by DorianDepriester** [comment]
I have added a file named [unitTest](https://github.com/DorianDepriester/MTEX2Gmsh/blob/master/docs/Examples/unitTest.m). It sums up all the examples given in the eponymous folder, plus it plots the geometry in each case.

**Comment by DorianDepriester** [comment]
Alternatively, I have update the code on code Ocean, following your recommendations (that is, provide multiple examples).

Tell me if if need to keep the aforementioned ``unitTest.m`` or/and the reference to the capsule.

**Comment by streeve** [comment]
I think `unitTest.m` is exactly what you want: it runs the main examples, is easy to extend, and you can run on Code Ocean or locally
