### ISSUE TITLE
[need some help] mesh-command fails

### ISSUE THREAD

**Issue by StefanHackemann** [DorianDepriester/MTEX2Gmsh#10]
Hello Dorian, 
maybe it is more a problem of python or gmsh, but the mesh-command of MTEX2Gmsh fails  - any idea of what I'm doing wrong?
Thanks
Stefan
>> mesh(G,'small.inp');
Info    : Running 'C:\gmsh480\gmsh.exe C:\Users\Stefa\AppData\Local\Temp\tpf2ba8dd2_169d_42f7_a970_0dcbd065c0e3 -o small.inp -v 4 -save' [Gmsh 4.8.0, 1 node, max. 1 thread]
Info    : Started on Tue Apr 06 20:08:11 2021
Info    : Reading 'C:\Users\Stefa\AppData\Local\Temp\tpf2ba8dd2_169d_42f7_a970_0dcbd065c0e3'...
Info    : Writing 'small.inp'...
Info    : Done writing 'small.inp'
Info    : Shell opening 'C:\Users\Stefa\gmsh-4.8.0-Windows64\tutorial\python\t1.py' with arguments ' -onelab "t1" 127.0.0.1:51647'
Error   : Abnormal server termination (Socket listening timeout on socket 127.0.0.1:0)
Info    : Shell opening 'C:\Users\Stefa\gmsh-4.8.0-Windows64\tutorial\python\t1.py' with arguments ' -onelab "t1" 127.0.0.1:51648'
Error   : Abnormal server termination (Socket listening timeout on socket 127.0.0.1:0)
Info    : Shell opening 'C:\Users\Stefa\gmsh-4.8.0-Windows64\tutorial\python\t1.py' with arguments ' -onelab "t1" 127.0.0.1:51650'
Error   : Abnormal server termination (Socket listening timeout on socket 127.0.0.1:0)
Info    : Saving database 'C:\Users\Stefa\AppData\Local\Temp\tpf2ba8dd2_169d_42f7_a970_0dcbd065c0e3.db'...
Info    : Done saving database 'C:\Users\Stefa\AppData\Local\Temp\tpf2ba8dd2_169d_42f7_a970_0dcbd065c0e3.db'
Info    : Stopped on Tue Apr 06 20:08:26 2021 (From start: Wall 15.1449s, CPU 0.03125s)
>>

**Comment by DorianDepriester** [comment]
This is very strange. As far as I understand, Gmsh opens tutorials files after reading and meshing your geometry.
Ayway, the mesh ``small.inp`` seems to be generated with success.

**Comment by StefanHackemann** [comment]
Hi Dorian, 
thanks for the quick response!

As I understand now, it is a problem of GMSH + firewall and maybe python(#3). 
But I can mesh with the savegeo-command and then open the .geo-file with GMSH. 
I guess I can live with that J
Thanks a lot!
Stefan 

 

Von: Dorian Depriester ***@***.*** 
Gesendet: Mittwoch, 7. April 2021 10:47
An: DorianDepriester/MTEX2Gmsh ***@***.***>
Cc: StefanHackemann ***@***.***>; Author ***@***.***>
Betreff: Re: [DorianDepriester/MTEX2Gmsh] [need some help] mesh-command fails (#10)

 

This is very strange. As far as I understand, Gmsh opens tutorials files after reading and meshing your geometry.
Ayway, the mesh small.inp seems to be generated with success.
