### ISSUE TITLE
Create more elements in Z direction

### ISSUE THREAD

**Issue by jdavidgg01** [DorianDepriester/MTEX2Gmsh#15]
Hello Dorian,

For the standard command it says: The above command results in a 1 element thick mesh
 so i was wondering if there is there a way to apply thickness and have more elements in Z direction?

Thank you
Regards

David.

**Comment by DorianDepriester** [comment]
Do you mean using tetrahedrons or wedge/hexahedrons?

**Comment by DorianDepriester** [comment]
Hello @jdavidgg01,
In case you are interested, I have just added a 'Layers' option for meshing ([1cc69be](https://github.com/DorianDepriester/MTEX2Gmsh/commit/1cc69be00d616de6f6611714fc3303033bab46b4)). For instance, if you want 3 wedge element in thickness (instead of 1):
````
G.mesh(file.msh, 'Layers', 3)
````
Does this comply with your needs?

**Comment by jdavidgg01** [comment]
Yes Dorian, that is exactly what i'm looking for, but i'm trying to run your updated code with the layers option but Matlab is giving me this error:

Not enough input arguments.

Error in mesh (line 99)
	[~,~,fext] = fileparts(filepath);

I don't know if i'm doing something wrong?

Regards

**Comment by DorianDepriester** [comment]
Are you sure you have update MTEX2Gmsh to the latest commit?

**Comment by DorianDepriester** [comment]
Oh, I have just noticed I have forgotten the quotes around the file name:
`````
G.mesh('file.msh', 'Layers', 3)
`````

Alternatively, you can try:
`````
mesh(G, 'file.msh', 'Layers', 3)
`````

**Comment by jdavidgg01** [comment]
Now is working Dorian, thank you so much!
