### ISSUE TITLE
matlab warnings

### ISSUE THREAD

**Issue by streeve** [DorianDepriester/MTEX2Gmsh#2]
This is an extremely minor issue: there are a handful of suggestions from the matlab warnings (extra semicolons, unnecessary variables) in the gmshGeo class

openjournals/joss-reviews#2094

**Comment by DorianDepriester** [comment]
The code analyzer shows neither error nor warning in all .m files (tested on Matlab 2013b and 2016a). Which editor do you use?

**Comment by streeve** [comment]
I was using 2018b

**Comment by DorianDepriester** [comment]
The warnings you've mentioned are now fixed (tested on MATLAB 2018a).
