### ISSUE TITLE
Paper revisions

### ISSUE THREAD

**Issue by streeve** [DorianDepriester/MTEX2Gmsh#3]
- [x] The paper may be more accessible to a general (materials science) audience if the first two sentences are flipped: grain morphology and texture are greatly important for materials behavior, and micromechanics is of great use to that end.
- [x] In paragraph 2 please note these are experimental techniques
- [x] Are you limited to a subset of phases based on implementation, or is it generalized? More specifically, you mention a cubic "criterion", but I do not understand the extension to the current work.
- [x] As I understand, your work builds on the previous by expanding to (contingent on the previous question) any phases/orientations by combining the two underlying codes - please make this explicit
- [x] Within the figure caption you recite mtex, but not gmsh

openjournals/joss-reviews#2094

**Comment by DorianDepriester** [comment]
Thank you @streeve 
All the items you mentioned have been taken into consideration. Please, check out the [new proof](https://github.com/openjournals/joss-reviews/issues/2094#issuecomment-590469247) and tell me if it fits with your taste.

**Comment by streeve** [comment]
Looks good to me
