### ISSUE TITLE
Incoherent Elements at grain boundaries

### ISSUE THREAD

**Issue by Max-EDFLMT** [DorianDepriester/MTEX2Gmsh#6]
Hi,

Firstly I would like to thank you for the powerful tool that already helped me a lot.

I've recently came across an issue with meshes generated with MTEX2Gmsh. Some grains have inconsistent element at boundaries with their surroundings. I have tried to generate the mesh in gmsh using the .geo file without extrusion, the same problem arises everytime in the same place i.e. if I mesh a small part of my microstructure where the previously incriminated grains is, the same problem persist. Everything seems ok in MTEX though. These grains have no connectivity with the rest of the mesh when performing FEM computations.

I attached a picture illustrating my issue. Have I done something wrong ?
![MTEX_issue](https://user-images.githubusercontent.com/59999085/103946910-93397700-5137-11eb-9e33-61e17a623cda.png)

Thanks in advance for the help.

EDIT : It seems that there are some wrong spline definitions getting the following gmsh warning "Wrong control point index in bspline"

Maxime

**Comment by DorianDepriester** [comment]
Hello Maxime,
Which Gmsh version do you use?

**Comment by Max-EDFLMT** [comment]
Hello Dorian,
I use the latest one (4.7.1). I tried a former one (4.4.1), nothing changes

**Comment by DorianDepriester** [comment]
Could you share the content of the geo file please (here or using e.g. PasteBin)?

**Comment by Max-EDFLMT** [comment]
Here it is !

The geo file is quite large, I can do something better if it is useful for you.
The grain in the example is Grain_47 / PhysicalVolume(47) etc ... (you know this better than me)

[G.txt](https://github.com/DorianDepriester/MTEX2Gmsh/files/5786053/G.txt)

**Comment by DorianDepriester** [comment]
Ok, thank you.
I have figured what's wrong; this is due to duplicates in line loops. It will try to make a patch asap.

In the meantime, here is a workaround for your case: in the geo file, change the following definition (l. 68258):
````
Plane Surface(197)={198,199,100,95,102,200};
````
to
````
Plane Surface(197)={198,199,100,95,102,47};
````
and it should be OK.

Regards

**Comment by Max-EDFLMT** [comment]
Thanks for your responsiveness !

There are multiples error of this type in my mesh, I guess I'll need to wait for the patch.

Best Regards

**Comment by DorianDepriester** [comment]
Here is the patch. Try with the newer version of MTEX2Gmsh and tell me how it goes.

**Comment by Max-EDFLMT** [comment]
Seems to work like a charm !

I still have the warning message "Wrong control point index in bspline" if it helps for other bugs fixing

Anyway thanks for that instant fix and again for the useful tool.

Maxime

**Comment by DorianDepriester** [comment]
Hello @Max-EDFLMT ,
Just to mention that commit 8f704a644d9d9e2bc335fce60aafaaecd7778fc5 adds verbosity option for the ``mesh()`` command. It helps turning off those warnings.
Regards

**Comment by Max-EDFLMT** [comment]
Hello Dorian,
Thanks for the info. I can reconfirm that everything works fine with numerous tests since my last message.
Best Regards
